image:
  name: registry.gitlab.com/gitlab-org/gitlab-build-images:terraform
  entrypoint:
    - 'usr/bin/env'
    - 'PATH/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: "us-east-1"

stages:
  - validate
  - plan 
  - apply
  - destroy

before_script:
  - terraform --version
  - terraform init

validate:
  stage: validate
  script:
    - terraform validate

plan: 
  stage: plan
  dependencies:
    - validate
  script:
   - terraform plan -out="planfile"
  artifacts:
    paths:
      - planfile
    when: on_success
    access: developer

apply:
  stage: apply
  dependencies:
    - plan
  script:
    - terraform apply -input=false planfile
  when: manual

destroy:
  stage: destroy
  script:
    - terraform destroy -auto-approve planfile
  when: manual
